# Generated by Django 5.2.4 on 2025-07-05 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_uuid_userpublickey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublickey',
            name='key_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpublickey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
