# Generated by Django 5.2.4 on 2025-07-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='key_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
